In [1]:
#Addition of two vectors

In [3]:
import numpy as np
a=np.array([2,3])
b=np.array([7,4])
print(a)
print(b)

[2 3]
[7 4]


In [4]:
print(a+b)

[9 7]


In [9]:
a+b

array([9, 7])

In [11]:
#Subtract two vectors

In [12]:
print(a-b)

[-5 -1]


In [13]:
#scalar multiplication
print(a)
b=2
print(b)
a*b

[2 3]
2


array([4, 6])

In [17]:
#dot product of two vectors is same as multiplication
a=np.array([2,4])
b=np.array([5,2])
print(a)
print(b)
print(2*5+4*2)
np.dot(a,b)

[2 4]
[5 2]
18


18

In [25]:
#matrics addition

In [27]:
a=np.array([[4,3,2],[6,3,7],[4,9,8]])
b=np.array([[3,4,2],[9,1,7],[6,4,8]])
print(a)
print(b)
a+b

[[4 3 2]
 [6 3 7]
 [4 9 8]]
[[3 4 2]
 [9 1 7]
 [6 4 8]]


array([[ 7,  7,  4],
       [15,  4, 14],
       [10, 13, 16]])

In [30]:
#matrics subtraction
a=np.array([[4,3,2],[6,3,7],[4,9,8]])
b=np.array([[3,4,2],[9,1,7],[6,4,8]])
print(a,end="= a\n\n")
print(b,end="= b\n\n")
a-b

[[4 3 2]
 [6 3 7]
 [4 9 8]]= a

[[3 4 2]
 [9 1 7]
 [6 4 8]]= b



array([[ 1, -1,  0],
       [-3,  2,  0],
       [-2,  5,  0]])

In [31]:
#scalar multiplication with matrix
s=4
s*a

array([[16, 12,  8],
       [24, 12, 28],
       [16, 36, 32]])

In [32]:
#matrix multiplication with vector
a=np.array([[4,5,6],[6,3,9]])
b=np.array([6,3,8])
np.dot(a,b)

array([ 87, 117])

In [35]:
#matrix to matrix multiplication
a=np.array([[4,5,6],[6,3,9]])
b=np.array([[6,3,8],[4,5,6],[4,5,3]])
np.dot(a,b)

array([[68, 67, 80],
       [84, 78, 93]])

In [38]:
a=np.array([[4,5,6],[6,3,9]])
b=np.array([[6,3,8],[4,5,6],[4,5,3]])
a*b

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [39]:
a=np.array([[4,5,6],[6,3,9]])
b=np.array([[6,3,8],[4,5,6]])
a*b

array([[24, 15, 48],
       [24, 15, 54]])

In [42]:
#transpose of a matrix
print(a,end="= a\n\n")
print(a.T,end="= aT\n\n")
print(b,end="= b\n\n")
print(b.T,end="= bT\n\n")

[[4 5 6]
 [6 3 9]]= a

[[4 6]
 [5 3]
 [6 9]]= aT

[[6 3 8]
 [4 5 6]]= b

[[6 4]
 [3 5]
 [8 6]]= bT



In [44]:
#creating a identity matrix
a1=np.eye(3)
print(a1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
#inverse of a matrix
#given A square matrix a
#return a matrix that satisfy dot(a,ainv)=dot(ainv,a)=eye(a.shape[0])
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.inv(a))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [54]:
#eigen values and eigen vectors
import numpy as np
def find_eig(matrix):
    if matrix.shape[0]!= matrix.shape[1]:
        raise ValueError("rows != cols")
    else:
        eigenvals,eigenvectors=np.linalg.eig(matrix)
        return eigenvals,eigenvectors
matrix=np.array([[2,3,4],[3,8,7],[6,9,4]])    
eigenvalues,eigenvectors=find_eig(matrix)
print(eigenvalues,eigenvectors,sep="\n\n")


[16.24952679  1.04580033 -3.29532712]

[[-0.32749216 -0.76039677 -0.39253044]
 [-0.6777305   0.59349982 -0.4069124 ]
 [-0.6583542  -0.26373228  0.82482856]]
